import { v4 as uuidv4 } from "uuid"; 

function chillHop() {
    return [

        {
            name:"Escambia County Area Marine",
            artist: "Marine Radio on the Inter-coastal in Escambia County Florida",
            cover: "https://cdn6.aptoide.com/imgs/6/d/2/6d23326ac7cc8f95fc00bf6dfeb6d256_icon.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://broadcastify.cdnstream1.com/31445",
            active: true,       
         },
        {   
            name:"Sault Sainte Marie Marine Ch-12 (Soo Traffic)",
            artist: "Also scans channels 8, 10, 14, and 16.",
            cover: "https://cdn6.aptoide.com/imgs/6/d/2/6d23326ac7cc8f95fc00bf6dfeb6d256_icon.png",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "https://broadcastify.cdnstream1.com/38764",
            active: false,
        },
        {
            
            name:"Mobile Alabama Bay Marine 13",
            artist: "This Feed also features Marine Channels 11,13,18 These channels are used while piloting large vessels up to the Mobile Port from the Gulf of Mexico.",
            cover: "https://cdn6.aptoide.com/imgs/6/d/2/6d23326ac7cc8f95fc00bf6dfeb6d256_icon.png",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "https://broadcastify.cdnstream1.com/22612",
            active: false,
        },
        {
            name:"Mobile Area NOAA Weather Radio KEC-61",
            artist: " You may hear low signal/fading signal at night!** This transmitter is located in Mobile Alabama and serves the following areas: In Alabama: Baldwin and Mobile. In Mississippi: George and Jackson. Mobile Bay and coastal waters out to 60NM from",
            cover: "https://www.audioescuelasabatica.com/wp-content/uploads/2022/12/Portada.jpg",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "https://broadcastify.cdnstream1.com/37430",
            active: false,
        },
        {
            name:"Pensacola Area NOAA Weather Radio KEC-86",
            artist: "This transmitter is located in Milton Florida and serves the following areas: In Alabama: Baldwin and Escambia. In Florida: Escambia, Santa Rosa, and Okaloosa. Coastal waters out to 60NM from shore.	",
            cover: "https://cdn6.aptoide.com/imgs/6/d/2/6d23326ac7cc8f95fc00bf6dfeb6d256_icon.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://broadcastify.cdnstream1.com/37380",
            active: false,
        },
        {
            name:"Baldwin County Fire and EMS, State Troopers",
            artist: "Alabama State Trooper: 155.445 MHz Fairhope Fire: 154.445 MHz Baldwin Co. 154.130 MHz 911 Fire North Baldwin Co. 154.385 MHz 911 Fire South Baldwin Co. 155.385 MHz 911 Fire East, 911 West 151.295, Escambia Co VFD Simplex. 154.430 MHz, Foley-Summerdale",
            cover: "https://cdn6.aptoide.com/imgs/6/d/2/6d23326ac7cc8f95fc00bf6dfeb6d256_icon.png",
            id: uuidv4(),
            color: ["#845648","#FDFBDF"],
            audio: "https://broadcastify.cdnstream1.com/25906",
            active: false,
        },
        {
            name:"New Orleans VTS Lower Mississippi Traffic",
            artist: "Orleans",
            cover: "https://cdn6.aptoide.com/imgs/6/d/2/6d23326ac7cc8f95fc00bf6dfeb6d256_icon.png",
            id: uuidv4(),
            color: ["#578CCE", "#E9D6D0"],
            audio: "https://broadcastify.cdnstream1.com/20198",
            active: false,       
        },
        {
            name:"Upper Chesapeake Bay 156.8 MHz Marine Ch-16",
            artist: "Anne Arundel",
            cover: "https://cdn6.aptoide.com/imgs/6/d/2/6d23326ac7cc8f95fc00bf6dfeb6d256_icon.png",
            id: uuidv4(),
            color: ["#7BC8DD", "#D64A59"],
            audio: "https://broadcastify.cdnstream1.com/35683",
            active: false,
        },
        {
            name:"Northern NJ and NY City Area Marine",
            artist: "This feed is VHF Marine radio for the Northern New Jersey and New York City area. Including the Hudson River, East River, New York Harbor, Newark Bay, Passaic and Hackensack Rivers, Raritan Bay and River, Atlantic Ocean and all surrounding waters. Enjoy..	",
            cover: "https://cdn6.aptoide.com/imgs/6/d/2/6d23326ac7cc8f95fc00bf6dfeb6d256_icon.png",
            id: uuidv4(),
            color: ["#7BC8DD", "#D64A59"],
            audio: "https://broadcastify.cdnstream1.com/17329",
            active: false,            
        },
        {
            name:"Massena Area Marine",
            artist: "Seaway Communications & Lock Operations",
            cover: "https://cdn6.aptoide.com/imgs/6/d/2/6d23326ac7cc8f95fc00bf6dfeb6d256_icon.png",
            id: uuidv4(),
            color: ["#7BC8DD", "#D64A59"],
            audio: "https://broadcastify.cdnstream1.com/31613",
            active: false,
        },
        {
            name:"Boston Harbor Marine VHF",
            artist: "Primarily commercial marine traffic on VHF channels 6, 12, 13, 16, 18, 20 and 22 as heard from the South Shore of Boston.",
            cover: "https://cdn6.aptoide.com/imgs/6/d/2/6d23326ac7cc8f95fc00bf6dfeb6d256_icon.png",
            id: uuidv4(),
            color: ["#7BC8DD", "#D64A59"],
            audio: "https://broadcastify.cdnstream1.com/34710",
            active: false,
        },
        {
            name:"Duluth-Superior Harbor Marine Traffic",
            artist: "Listen to Lakers, freighters and tugs as the go about their nautical business in the Duluth-Superior Harbor.",
            cover: "https://cdn6.aptoide.com/imgs/6/d/2/6d23326ac7cc8f95fc00bf6dfeb6d256_icon.png",
            id: uuidv4(),
            color: ["#7BC8DD", "#D64A59"],
            audio: "https://broadcastify.cdnstream1.com/37404",
            active: false,
        },
        {
            name:"Kitsap County Area Marine",
            artist: "This feed will cover Kitsap and surrounding counties Marine broadcast. Most VHF marine band frequencies covered.",
            cover: "https://cdn6.aptoide.com/imgs/6/d/2/6d23326ac7cc8f95fc00bf6dfeb6d256_icon.png",
            id: uuidv4(),
            color: ["#7BC8DD", "#D64A59"],
            audio: "https://broadcastify.cdnstream1.com/26694",
            active: false,
        },
        {
            name:"San Francisco Bay Marine Traffic",
            artist: "Pillar Point Harbor Marine Radio Traffic",
            cover: "https://cdn6.aptoide.com/imgs/6/d/2/6d23326ac7cc8f95fc00bf6dfeb6d256_icon.png",
            id: uuidv4(),
            color: ["#7BC8DD", "#D64A59"],
            audio: "https://broadcastify.cdnstream1.com/36119",
            active: false,    
        },
    ];
}

export default chillHop;


